//
//  main.m
//  Euler2
//
//  Created by JohanLundgren on 2015-10-12.
//  Copyright (c) 2015 SuperMilkApps. All rights reserved.
//

#import <Foundation/Foundation.h>

/* Problem 2*/

/*Uppgiftsbeskrivningen lyder:
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

/*För att lösa den här uppgiften behöver vi dels ta reda på vilka nummer i serien som är jämna och sedan addera dessa. Eftersom nästkommande nummer i Fibonacciserien kan uttryckas enligt n = (n-1) + (n-2) behöver vi dels två variabler som uttrycker n-1 och n-2, en variabel som håller det aktuella nummret som uttrycks med hjälp av n-1 och n-2 och en variabel som håller reda på summan av alla jämna tal.*/

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        
        //Deklarerar och initialiserar variabler
        long fNum1 = 0;
        long fNum2 = 1;
        long fNyttNum = 0;
        long summa = 0;
        
        //Då fNum2 representerar det högsta nummret kommer det vara det som går över 4,000,000 först och det är därför det som får vara argumentet för while-loopen. Det som sedan händer är att, för varje iteration, fNyttNum får det sammanlagda värdet av fNum1 och fNum2 vilket alltså kommer vara nästa nummer i Fibonacciserien, vilket två rader längre ner tilldelas till fNum2. fNum1 får vidare värdet av fNum2 vilket alltså blir nästa nummer i Fibonacciserien, för fNum1. Det kontrolleras sedan om fNum2, som alltså är det högsta rådande nummret för varje iteration, inte ger någon rest vid division med 2, och därmed är jämnt. Om den gör detta läggs värdet av den till i summavariabeln och loopen körs sedan om på nytt tills argumentet för whileloopen inte längre är sant, det vill säga när fNum2 inte länger är mindre än 4000000.
        while (fNum2 < 4000000) {
            fNyttNum = fNum1 + fNum2;
            fNum1 = fNum2;
            fNum2 = fNyttNum;
            if ((fNum2 % 2) == 0) {
                summa += fNum2;
            }
        }
        
        //Summan av alla jämna termer skrivs sedan ut
        NSLog(@"Summan av alla jämna termer i Fibonacci-serien är: %ld", summa);
    }
    return 0;
}

/*Källor: https://en.wikipedia.org/wiki/Fibonacci_number */
